name = "Copulas"
uuid = "ae264745-0b69-425e-9d9d-cf662c5eec93"
authors = ["Oskar Laverny"]
version = "0.1.0"

[compat]
julia = "1.5.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
